#:schema node_modules/wrangler/config-schema.json
name = "peculiarnewbie"
compatibility_date = "2025-01-09"
assets = { directory = "./dist/" }
# main = "./dist/rss.xml"
# assets = { directory = "./dist", binding = "ASSETS" }
