#:schema node_modules/wrangler/config-schema.json
name = "peculiarnewbie"
compatibility_date = "2025-01-09"
compatibility_flags = ["nodejs_compat"]
main = "./dist/_worker.js/index.js"
assets = { directory = "./dist", binding = "ASSETS" }
